//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFESPLib.NFEPrefeituraSaoPauloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="NFEPrefeituraSaoPauloService.LoteNFeSoap")]
    public interface LoteNFeSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (EnvioRPSRequest) of message EnvioRPSRequest does not match the default value (EnvioRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSResponse EnvioRPS(NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSResponse> EnvioRPSAsync(NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (EnvioLoteRPSRequest) of message EnvioLoteRPSRequest does not match the default value (EnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSResponse EnvioLoteRPS(NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSResponse> EnvioLoteRPSAsync(NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (TesteEnvioLoteRPSRequest) of message TesteEnvioLoteRPSRequest does not match the default value (TesteEnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CancelamentoNFeRequest) of message CancelamentoNFeRequest does not match the default value (CancelamentoNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeResponse CancelamentoNFe(NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeResponse> CancelamentoNFeAsync(NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaNFeRequest) of message ConsultaNFeRequest does not match the default value (ConsultaNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeResponse ConsultaNFe(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeResponse> ConsultaNFeAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaNFeRecebidasRequest) of message ConsultaNFeRecebidasRequest does not match the default value (ConsultaNFeRecebidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaNFeEmitidasRequest) of message ConsultaNFeEmitidasRequest does not match the default value (ConsultaNFeEmitidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaLoteRequest) of message ConsultaLoteRequest does not match the default value (ConsultaLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteResponse ConsultaLote(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteResponse> ConsultaLoteAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaInformacoesLoteRequest) of message ConsultaInformacoesLoteRequest does not match the default value (ConsultaInformacoesLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaCNPJRequest) of message ConsultaCNPJRequest does not match the default value (ConsultaCNPJ)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJResponse ConsultaCNPJ(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJResponse> ConsultaCNPJAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequest() {
        }
        
        public EnvioRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponse() {
        }
        
        public EnvioRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequest() {
        }
        
        public EnvioLoteRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponse() {
        }
        
        public EnvioLoteRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequest() {
        }
        
        public TesteEnvioLoteRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponse() {
        }
        
        public TesteEnvioLoteRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequest() {
        }
        
        public CancelamentoNFeRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponse() {
        }
        
        public CancelamentoNFeResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequest() {
        }
        
        public ConsultaNFeRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponse() {
        }
        
        public ConsultaNFeResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequest() {
        }
        
        public ConsultaNFeRecebidasRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponse() {
        }
        
        public ConsultaNFeRecebidasResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequest() {
        }
        
        public ConsultaNFeEmitidasRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponse() {
        }
        
        public ConsultaNFeEmitidasResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequest() {
        }
        
        public ConsultaLoteRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponse() {
        }
        
        public ConsultaLoteResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequest() {
        }
        
        public ConsultaInformacoesLoteRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponse() {
        }
        
        public ConsultaInformacoesLoteResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequest() {
        }
        
        public ConsultaCNPJRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponse() {
        }
        
        public ConsultaCNPJResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoteNFeSoapChannel : NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap>, NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap {
        
        public LoteNFeSoapClient() {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.EnvioRPS(NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest request) {
            return base.Channel.EnvioRPS(request);
        }
        
        public string EnvioRPS(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).EnvioRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.EnvioRPSAsync(NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest request) {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSResponse> EnvioRPSAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).EnvioRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.EnvioLoteRPS(NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPS(request);
        }
        
        public string EnvioLoteRPS(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).EnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.EnvioLoteRPSAsync(NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSResponse> EnvioLoteRPSAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).EnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.TesteEnvioLoteRPS(NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPS(request);
        }
        
        public string TesteEnvioLoteRPS(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).TesteEnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.TesteEnvioLoteRPSAsync(NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).TesteEnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.CancelamentoNFe(NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFe(request);
        }
        
        public string CancelamentoNFe(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).CancelamentoNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.CancelamentoNFeAsync(NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeResponse> CancelamentoNFeAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).CancelamentoNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaNFe(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFe(request);
        }
        
        public string ConsultaNFe(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaNFeAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeResponse> ConsultaNFeAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaNFeRecebidas(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidas(request);
        }
        
        public string ConsultaNFeRecebidas(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaNFeRecebidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaNFeRecebidasAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaNFeRecebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaNFeEmitidas(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidas(request);
        }
        
        public string ConsultaNFeEmitidas(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaNFeEmitidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaNFeEmitidasAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaNFeEmitidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaLote(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLote(request);
        }
        
        public string ConsultaLote(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaLoteAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteResponse> ConsultaLoteAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaInformacoesLote(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLote(request);
        }
        
        public string ConsultaInformacoesLote(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaInformacoesLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaInformacoesLoteAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaInformacoesLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJResponse NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaCNPJ(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJ(request);
        }
        
        public string ConsultaCNPJ(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJResponse retVal = ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaCNPJ(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJResponse> NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap.ConsultaCNPJAsync(NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJResponse> ConsultaCNPJAsync(int VersaoSchema, string MensagemXML) {
            NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest inValue = new NFESPLib.NFEPrefeituraSaoPauloService.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NFESPLib.NFEPrefeituraSaoPauloService.LoteNFeSoap)(this)).ConsultaCNPJAsync(inValue);
        }
    }
}
